### ISSUE TITLE
Expose more information to enable pan/zoom/rotation

### ISSUE THREAD

**Issue by rreusser** [Jam3/touch-pinch#1]
This module is very useful. Together with [mouse-event](https://www.npmjs.com/package/mouse-event), it got me pretty far toward solving my interaction goals. I had to tack on additional features though to get it to pan and pinch smoothly (e.g. you pinch but then one finger leaves and it turns smoothly into a pan).

You can see an example here (enabled if Modernizr.touchevents === true): https://rreusser.github.io/grid-generation-experiments/
The code for panning/pinching is here: [viewport.js#L97-L179](https://github.com/rreusser/grid-generation-experiments/blob/master/src/master/lib/viewport.js#L97-L179)

My code is mostly garbage, but the pattern is pretty straightforward and self-contained and with lots of cleanup seems like it has a home somewhere. Specifically, I found that distance between fingers wasn't quite enough information for me, so I had to dig a little and expose a bit more. It seems to me that a `transform` event that exposes translation, scaling, and optionally rotation would be a natural addition that could be easily be plugged into a transformation matrix.

So my question is this: Does a module like this already exist? I'd be glad to submit a PR if you think there are reasonable additions to this module, but I also don't want to fall into feature creep for what's otherwise a perfectly useful and straightforward module. Thanks!

**Comment by mattdesl** [comment]
Thanks for testing it out. :smile: 

How do you think the API would look? I'd be willing to accept a PR for `transform`.

Myself and @tatumcreative will be using this module for panning/zooming/etc in [orbit-controls](https://github.com/Jam3/orbit-controls), it looks like your PR would help move things along. :+1:

**Comment by rreusser** [comment]
Gotcha. Yeah, my concern at the moment is 2D-oriented. `orbit-controls` is exactly what I was wondering about though. It felt like this was getting plugged into something, but I wasn't sure what. I'll put some thought into this and see if I can isolate the minimal additional amount of info I'd need to expose to get what I need out of it.

Things I'm interested in exposing:
- one finger panning
- two finger pinching (yields information about pan, zoom, and rotation)
- inertia (not as part of this; would look like a wrapper that plugs into position and velocity and continues triggering view changes, perhaps…)

Of course although it's 2D information, its usefulness would not be limited to 2D.

I'll think about this and see if I can clean up these thoughts. Thanks for the feedback!

**Comment by rreusser** [comment]
As seen on twitter, I've slowly been refining some of these ideas and it's led to: https://github.com/rreusser/normalized-interaction-events. There are parts I don't love about it, but it feels like a useful direction at least. I realized a big part of what was bothering me was always converting back and forth between clip space and viewport space, as well has having to pull in separate modules for touch and mouse behavior. I'm not sure if it's the right level at which to roll it up, but I sorta like it. A nice result is that you can connect events to a camera with little translation and pretty much all business logic. Still improvement to be made though.

One subtlety is that theta is not so meaningful in clip space so that you still have to enter an aspect ratio to get that right. I could be convinced that that should simply go away in favor of the touch coords, though it is a nice convenience.

It'll never be perfect, but I'll just go ahead and close this so I can breathe a small sigh of relief.
